# Generated by Django 4.0.6 on 2022-08-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_activo_historicaluser_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='is_active',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='activo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
