# Generated by Django 4.0.6 on 2022-07-12 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('creation_date', models.DateField(verbose_name=datetime.datetime(2022, 7, 12, 19, 3, 37, 426108))),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
