# Generated by Django 4.0.6 on 2022-07-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='Asunto del ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='Asunto del ticket'),
        ),
    ]
