# Generated by Django 4.0.6 on 2022-07-20 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_historicalticket_subject_alter_ticket_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='ticket_urgency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tickets.ticketurgency', verbose_name='Urgencia del ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_urgency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketurgency', verbose_name='Urgencia del ticket'),
        ),
    ]
